export interface TimezoneOption {
  label: string;
  value: number | 'exchange';
}

export const TIMEZONE_OPTIONS: TimezoneOption[] = [
  { label: 'UTC', value: 0 },
  { label: 'Exchange', value: 'exchange' },
  { label: '(UTC-10) Honolulu', value: -600 },
  { label: '(UTC-8) Anchorage', value: -480 },
  { label: '(UTC-8) Juneau', value: -480 },
  { label: '(UTC-7) Los Angeles', value: -420 },
  { label: '(UTC-7) Phoenix', value: -420 },
  { label: '(UTC-7) Vancouver', value: -420 },
  { label: '(UTC-6) Denver', value: -360 },
  { label: '(UTC-6) Mexico City', value: -360 },
  { label: '(UTC-6) San Salvador', value: -360 },
  { label: '(UTC-5) Bogota', value: -300 },
  { label: '(UTC-5) Chicago', value: -300 },
  { label: '(UTC-5) Lima', value: -300 },
  { label: '(UTC-4) Caracas', value: -240 },
  { label: '(UTC-4) New York', value: -240 },
  { label: '(UTC-4) Santiago', value: -240 },
  { label: '(UTC-4) Toronto', value: -240 },
  { label: '(UTC-3) Buenos Aires', value: -180 },
  { label: '(UTC-3) Halifax', value: -180 },
  { label: '(UTC-3) Sao Paulo', value: -180 },
  { label: '(UTC) Azores', value: 0 },
  { label: '(UTC) Reykjavik', value: 0 },
  { label: '(UTC+1) Casablanca', value: 60 },
  { label: '(UTC+1) Dublin', value: 60 },
  { label: '(UTC+1) Lagos', value: 60 },
  { label: '(UTC+1) Lisbon', value: 60 },
  { label: '(UTC+1) London', value: 60 },
  { label: '(UTC+1) Tunis', value: 60 },
  { label: '(UTC+2) Amsterdam', value: 120 },
  { label: '(UTC+2) Belgrade', value: 120 },
  { label: '(UTC+2) Berlin', value: 120 },
  { label: '(UTC+2) Bratislava', value: 120 },
  { label: '(UTC+2) Brussels', value: 120 },
  { label: '(UTC+2) Budapest', value: 120 },
  { label: '(UTC+2) Copenhagen', value: 120 },
  { label: '(UTC+2) Johannesburg', value: 120 },
  { label: '(UTC+2) Ljubljana', value: 120 },
  { label: '(UTC+2) Luxembourg', value: 120 },
  { label: '(UTC+2) Madrid', value: 120 },
  { label: '(UTC+2) Malta', value: 120 },
  { label: '(UTC+2) Oslo', value: 120 },
  { label: '(UTC+2) Paris', value: 120 },
  { label: '(UTC+2) Prague', value: 120 },
  { label: '(UTC+2) Rome', value: 120 },
  { label: '(UTC+2) Stockholm', value: 120 },
  { label: '(UTC+2) Vienna', value: 120 },
  { label: '(UTC+2) Warsaw', value: 120 },
  { label: '(UTC+2) Zagreb', value: 120 },
  { label: '(UTC+2) Zurich', value: 120 },
  { label: '(UTC+3) Athens', value: 180 },
  { label: '(UTC+3) Bahrain', value: 180 },
  { label: '(UTC+3) Bucharest', value: 180 },
  { label: '(UTC+3) Cairo', value: 180 },
  { label: '(UTC+3) Helsinki', value: 180 },
  { label: '(UTC+3) Istanbul', value: 180 },
  { label: '(UTC+3) Jerusalem', value: 180 },
  { label: '(UTC+3) Kuwait', value: 180 },
  { label: '(UTC+3) Moscow', value: 180 },
  { label: '(UTC+3) Nairobi', value: 180 },
  { label: '(UTC+3) Nicosia', value: 180 },
  { label: '(UTC+3) Qatar', value: 180 },
  { label: '(UTC+3) Riga', value: 180 },
  { label: '(UTC+3) Riyadh', value: 180 },
  { label: '(UTC+3) Sofia', value: 180 },
  { label: '(UTC+3) Tallinn', value: 180 },
  { label: '(UTC+3) Vilnius', value: 180 },
  { label: '(UTC+3:30) Tehran', value: 210 },
  { label: '(UTC+4) Dubai', value: 240 },
  { label: '(UTC+4) Muscat', value: 240 },
  { label: '(UTC+4:30) Kabul', value: 270 },
  { label: '(UTC+5) Ashgabat', value: 300 },
  { label: '(UTC+5) Astana', value: 300 },
  { label: '(UTC+5) Karachi', value: 300 },
  { label: '(UTC+5:30) Colombo', value: 330 },
  { label: '(UTC+5:30) Kolkata', value: 330 },
  { label: '(UTC+5:45) Kathmandu', value: 345 },
  { label: '(UTC+6) Dhaka', value: 360 },
  { label: '(UTC+6:30) Yangon', value: 390 },
  { label: '(UTC+7) Bangkok', value: 420 },
  { label: '(UTC+7) Ho Chi Minh', value: 420 },
  { label: '(UTC+7) Jakarta', value: 420 },
  { label: '(UTC+8) Chongqing', value: 480 },
  { label: '(UTC+8) Hong Kong', value: 480 },
  { label: '(UTC+8) Kuala Lumpur', value: 480 },
  { label: '(UTC+8) Manila', value: 480 },
  { label: '(UTC+8) Perth', value: 480 },
  { label: '(UTC+8) Shanghai', value: 480 },
  { label: '(UTC+8) Singapore', value: 480 },
  { label: '(UTC+8) Taipei', value: 480 },
  { label: '(UTC+9) Seoul', value: 540 },
  { label: '(UTC+9) Tokyo', value: 540 },
  { label: '(UTC+9:30) Adelaide', value: 570 },
  { label: '(UTC+10) Brisbane', value: 600 },
  { label: '(UTC+10) Sydney', value: 600 },
  { label: '(UTC+11) Norfolk Island', value: 660 },
  { label: '(UTC+12) New Zealand', value: 720 },
  { label: '(UTC+12:45) Chatham Islands', value: 765 },
  { label: '(UTC+13) Tokelau', value: 780 },
];
